FROM ghcr.io/storydocker/storydocker:main

WORKDIR /usr/src/app

# This is optional. Sets the level of logging that you see
ENV NPM_CONFIG_LOGLEVEL verbose

COPY ./ ./workspaces/application
COPY ./.dockerignore ./
RUN npm i && npm cache clean --force
RUN npm i concurrently -g
RUN npm update vite

# Make storybook port available externally
EXPOSE 6001-6004
EXPOSE 6006

# run storybook app
CMD ["npm", "run", "storybook", "-workspace", "workspaces/application/"]
