// This file is auto-generated by <root>/generator/index.js, manual edits will be overwritten

export default {
  "vite_lit": {
    "title": "vite-lit",
    "directory": "vite-lit",
    "port": 6001,
    "local": "http://localhost:6001",
    "ghpages": "/storydocker-examples/vite-lit",
    "expanded": false
  },
  "vite_lit_ts": {
    "title": "vite-lit-ts",
    "directory": "vite-lit-ts",
    "port": 6002,
    "local": "http://localhost:6002",
    "ghpages": "/storydocker-examples/vite-lit-ts",
    "expanded": false
  },
  "vite_preact": {
    "title": "vite-preact",
    "directory": "vite-preact",
    "port": 6003,
    "local": "http://localhost:6003",
    "ghpages": "/storydocker-examples/vite-preact",
    "expanded": false
  },
  "vite_preact_ts": {
    "title": "vite-preact-ts",
    "directory": "vite-preact-ts",
    "port": 6004,
    "local": "http://localhost:6004",
    "ghpages": "/storydocker-examples/vite-preact-ts",
    "expanded": false
  },
  "vite_react": {
    "title": "vite-react",
    "directory": "vite-react",
    "port": 6005,
    "local": "http://localhost:6005",
    "ghpages": "/storydocker-examples/vite-react",
    "expanded": false
  },
  "vite_react_ts": {
    "title": "vite-react-ts",
    "directory": "vite-react-ts",
    "port": 6006,
    "local": "http://localhost:6006",
    "ghpages": "/storydocker-examples/vite-react-ts",
    "expanded": false
  },
  "vite_svelte": {
    "title": "vite-svelte",
    "directory": "vite-svelte",
    "port": 6007,
    "local": "http://localhost:6007",
    "ghpages": "/storydocker-examples/vite-svelte",
    "expanded": false
  },
  "vite_svelte_ts": {
    "title": "vite-svelte-ts",
    "directory": "vite-svelte-ts",
    "port": 6008,
    "local": "http://localhost:6008",
    "ghpages": "/storydocker-examples/vite-svelte-ts",
    "expanded": false
  },
  "vite_vanilla": {
    "title": "vite-vanilla",
    "directory": "vite-vanilla",
    "port": 6009,
    "local": "http://localhost:6009",
    "ghpages": "/storydocker-examples/vite-vanilla",
    "expanded": false
  },
  "vite_vanilla_ts": {
    "title": "vite-vanilla-ts",
    "directory": "vite-vanilla-ts",
    "port": 6010,
    "local": "http://localhost:6010",
    "ghpages": "/storydocker-examples/vite-vanilla-ts",
    "expanded": false
  },
  "vite_vue": {
    "title": "vite-vue",
    "directory": "vite-vue",
    "port": 6011,
    "local": "http://localhost:6011",
    "ghpages": "/storydocker-examples/vite-vue",
    "expanded": false
  },
  "vite_vue_ts": {
    "title": "vite-vue-ts",
    "directory": "vite-vue-ts",
    "port": 6012,
    "local": "http://localhost:6012",
    "ghpages": "/storydocker-examples/vite-vue-ts",
    "expanded": false
  }
}